ARG BASE_IMAGE_VERSION=latest-lts
FROM sourcepole/qwc-map-viewer-base:$BASE_IMAGE_VERSION

ARG QWC2_URL
# Optional token for download with authorization
ARG AUTH_TOKEN

RUN wget -O /tmp/appbundle.zip --header="PRIVATE-TOKEN: $AUTH_TOKEN" "$QWC2_URL" && \
    cd /tmp && \
    unzip appbundle.zip && \
    cd prod && \
    mkdir /qwc2 && mv * /qwc2 && \
    mkdir /qwc2/data && \
    rm -rf appbundle.zip
